# Generated by Django 4.2.1 on 2023-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_watchlist_watchlist_watchlist_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(related_name='watch', to='auctions.list'),
        ),
    ]
