# Generated by Django 4.2.1 on 2023-06-28 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
