# Generated by Django 4.2.1 on 2023-06-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_list_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.list'),
        ),
    ]
