# Generated by Django 4.2.1 on 2023-06-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_name_bid_user_remove_bid_bid_bid_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
